FROM python:3.9
WORKDIR /app_admin
COPY requirements.txt .
RUN pip install --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org --no-cache-dir -r requirements.txt
COPY app_admin.py /app_admin.py
COPY . . 
EXPOSE 5002
CMD ["python", "app_admin.py"]  
